### ISSUE TITLE
I got an error trying your codes. can you help me?

### ISSUE THREAD

**Issue by zzzniczxz** [V-Nico/codecommit-discord-notifier#1]
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'index'\nRequire stack:\n- /var/runtime/index.mjs",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'index'",
    "Require stack:",
    "- /var/runtime/index.mjs",
    "    at _loadUserApp (file:///var/runtime/index.mjs:996:17)",
    "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1031:21)",
    "    at async start (file:///var/runtime/index.mjs:1194:23)",
    "    at async file:///var/runtime/index.mjs:1200:1"
  ]
}

**Comment by V-Nico** [comment]
Hi,
It seems that the package does not work with lambda on node 18, you can use node v16.
